on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - name: Set API Key
      run: echo "API_Key=12345" >> $GITHUB_ENV
    - run: |
        dep= false
        if [[ dep ]]; then
          echo "::warning::Using API Key $API_Key"
        fi
